config/routes.rb
Rails.application.routes.draw do
  resources :products
  get 'home/index'
  resources :users do
    resources :lists
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :products, dependent: :destroy

  before_save :check_bought

  accepts_nested_attributes_for :products, reject_if: lambda { |a| a[:name].blank? }, allow_destroy: true

  def check_bought
    self.bought = products.map(&:bought).all?(true)
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :list

  validates_presence_of :name

  # validates_associated :price, greater_than: 0
end

app/models/user.rb
class User < ApplicationRecord
  has_many :lists, dependent: :destroy
  has_many :products, through: :lists, dependent: :destroy

  validates_presence_of :name
  validates_uniqueness_of :name

  validates_presence_of :birth_date

  before_save :capitalize_name

  def capitalize_name
    self.name = self.name.capitalize
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_user
  before_action :set_list, only: %i[ show edit update destroy ]

  # GET /lists or /lists.json
  def index
    @lists = @user.lists.all
  end

  # GET /lists/1 or /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = @user.lists.new
    10.times{@list.products.build}
  end

  # GET /lists/1/edit
  def edit
    1.times{@list.products.build}
  end

  # POST /lists or /lists.json
  def create
    @list = @user.lists.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to user_list_url(@user, @list), notice: "List was successfully created." }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1 or /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to user_list_url(@user, @list), notice: "List was successfully updated." }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1 or /lists/1.json
  def destroy
    @list.destroy

    respond_to do |format|
      format.html { redirect_to user_lists_url, notice: "List was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    def set_user
      @user = User.find_by(id: params[:user_id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:due_date, :bought, products_attributes: [:id, :name, :price, :bought])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.fetch(:product, {})
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :birth_date, :gender)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home</h1>
<p>This is an app for mannaging shopping lists</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to "Users", users_path, class: 'navbar-brand'%>
        <div class="collapse navbar-collapse">
          <div class="navbar-nav">
            <%= link_to 'Home', root_path, class: 'nav-item nav-link' %>
          </div>
        </div>
    </nav>
    <main class="container" role="main">
      <%= yield %>
    </main>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: [list.user, list]) do |form| %>
  <% if list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="input-group flex-nowrap">
    <%= form.label :due_date, "Due date", :class=>"input-group-text"%>
    <%= form.date_field :due_date,  :class=>"form-control" %>
  </div>

  <div>
    <%= form.fields_for :products do |builder|%>
      <%= render "products_fields", f: builder%>
    <%end%>
  </div>

  <div>
    <%= form.submit :class => "btn btn-success"%>
  </div>
<% end %>

app/views/lists/_list.html.erb
<div id="<%= dom_id list %>">
<p class="h3"><strong>Due date:</strong> <%= list.due_date%></p>
<% if list.bought %>
    <div id="container" style="background-color:#5cb85c; display:table; " class="mb-3 px-3 py-1 rounded" >
        This list has been bought
    </div>
<%else%>
<div style="background-color:#d9534f; display:table; " class="mb-3 px-3 py-1 rounded">
        This list has not been bought yet
    </div>


<%end%>
</div>

app/views/lists/_products_fields.html.erb
<p class="fields input-group flex-nowrap mt-3">
    <%= f.label :name, "Name", :class=>"input-group-text"%>
    <%= f.text_field :name, :class=>"form-control"%>

    <%= f.label :price, "Price", :class=>"input-group-text"%>
    <%= f.number_field :price, :class=>"form-control"%>

    <%= f.label :bought, "bought", :class=>"pl-3 form-check-label"%>
    <%= f.check_box :bought, :class=>"form-check-input" %>



</p>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render "form", list: @list %>

<br>

<div>
  <%= link_to "Show this list", [@list.user, @list], :class=>"btn btn-primary me-2"%>
  <%= link_to "Back to lists", user_lists_path, :class=>"btn btn-secondary me-2"  %>
</div>

app/views/lists/index.html.erb
<p style="color: green"><%= notice %></p>

<p class="h1">Lists</p>

<div id="lists">
  <% @lists.each do |list| %>
  <hr>
    <%= render list %>
    <p>
      <%= link_to "Show this list", [list.user, list], :class=>"btn btn-info" %>
    </p>
  <% end %>
</div>

<hr>
<%= link_to "New list", new_user_list_path, :class=>"btn btn-success" %>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render "form", list: @list %>

<br>

<div>
  <%= link_to "Back to lists", user_lists_path, :class=>"btn btn-secondary me-2"  %>
</div>

app/views/lists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @list %>

<hr>

<%# <%= @list.products.map(&:name)%>

<% @list.products.each do |product|%>

  <%if product.bought%>
  <div style="background-color: #5cb85c; display:table;" class="mb-3 px-3 py-1 rounded">
    <strong>Product: </strong><%= product.name %><strong>$</strong> <%= product.price %> <strong>Bought</strong>
   </div>
    <%else%>
    <div style="background-color: #d9534f; display:table;" class="mb-3 px-3 py-1 rounded">
      <strong>Product: </strong><%= product.name %><strong>$</strong> <%= product.price %> <strong>Not bought</strong>
    </div>
  <%end%>
<%end%>

<hr>

<div>
  <%= link_to "Edit this list", edit_user_list_path, :class=> "btn btn-primary me-2"%>
  <%= link_to "Back to lists", user_lists_path, :class=>"btn btn-secondary me-2" %>

  <%= button_to "Destroy this list", [@list.user, @list], method: :delete, :class => "btn btn-danger mt-2" %>

</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group flex-nowrap">
    <%= form.label :name, "User's name", :class=>"input-group-text"%>
    <%= form.text_field :name, :class=>"form-control"%>
  </div>

  <div class="input-group flex-nowrap my-3">
    <%= form.label :birth_date, "Birth date  ", :class=>"input-group-text" %>
    <%= form.date_field :birth_date, :class=>"form-control" %>
  </div>


  <div >
    <%= form.submit :class=> "btn btn-success" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">

    <p class="h3"><strong>Name:</strong> <%= user.name.capitalize %></p>
    <p><strong>ID:</strong> <%= user.id%></p>
    <p><strong>Birth date: </strong><%=user.birth_date%></p>
</div>

app/views/users/edit.html.erb
<p class="h1">Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user, :class=>"btn btn-primary me-2" %>
  <%= link_to "Back to users", users_path, :class=>"btn btn-secondary me-2" %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <hr>
    <%= render user %>
    <p>
      <%= link_to "Show", user, :class => "btn btn-info" %>
      <%= button_to "Delete", user, method: :delete, :class => "btn btn-danger"%>
    </p>
  <% end %>
</div>

<hr>
<%= link_to "New user", new_user_path, :class => "btn btn-success"%>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path, :class=>"btn btn-secondary me-2" %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user), :class=> "btn btn-primary me-2" %>
  <%= link_to "Back to users", users_path, :class=>"btn btn-secondary me-2" %>
  <%= link_to 'Lists', user_lists_path(@user), :class=>"btn btn-success me-2"%>

    <%= button_to "Destroy this user", @user, method: :delete, :class => "btn btn-danger mt-3" %>
</div>